### ISSUE TITLE
Fix travis

### ISSUE THREAD

**Issue by ewallah** [FormulasQuestion/moodle-qtype_formulas#13]
Travis integration is [not working](https://travis-ci.org/github/dbauer-ets/moodle-qtype_formulas/jobs/700982934)

With a correct [.travis.yml file](https://github.com/ewallah/moodle-qtype_formulas/blob/MOODLE_38_STABLE/.travis.yml),  travis works [again](https://travis-ci.org/github/ewallah/moodle-qtype_formulas/jobs/701020249).

**Comment by PhilippImhof** [comment]
This will be fixed with #35, where we move to GHA instead of Travis.
