### ISSUE TITLE
Fix phpunit

### ISSUE THREAD

**Issue by ewallah** [FormulasQuestion/moodle-qtype_formulas#14]
phpunit is [failing](https://travis-ci.org/github/ewallah/moodle-qtype_formulas/jobs/700986825#L420).

[This file](https://github.com/ewallah/moodle-qtype_formulas/blob/master/tests/questiontype_test.php) is [working](https://travis-ci.org/github/ewallah/moodle-qtype_formulas/jobs/701020249#L413)

 RUN  PHPUnit tests for qtype_formulas
Moodle 3.8.3+ (Build: 20200618), 898415efec81bc62bde20b862d1b139407a7329a
Php: 7.3.14, pgsql: 9.6.17, OS: Linux 5.0.0-1031-gcp x86_64
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.
.......................................................           55 / 55 (100%)
Time: 3.54 seconds, Memory: 254.50 MB
OK (55 tests, 748 assertions)

These test still should be reviewed completely.

**Comment by PhilippImhof** [comment]
This will be fixed with #35
