### ISSUE TITLE
Fix behat

### ISSUE THREAD

**Issue by ewallah** [FormulasQuestion/moodle-qtype_formulas#15]
Behat tests are now [failing](https://travis-ci.org/github/ewallah/moodle-qtype_formulas/jobs/700986826#L473)

[Some changes](https://github.com/dbauer-ets/moodle-qtype_formulas/commit/a68081b5d229e901a6f39c08ac2b68c93ff2a44d) make behat [happy](https://travis-ci.org/github/ewallah/moodle-qtype_formulas/jobs/701020249#L456) in Firefox and Chrome.

$ moodle-plugin-ci behat
 RUN  Behat features for qtype_formulas
Running single behat site:
Moodle 3.8.3+ (Build: 20200618), 898415efec81bc62bde20b862d1b139407a7329a
Php: 7.3.14, pgsql: 9.6.17, OS: Linux 5.0.0-1031-gcp x86_64
Server OS "Linux", Browser: "firefox"
Browser specific fixes have been applied.
Started at 23-06-2020, 04:06
...................................................................... 70
............................................................
7 scenarios (7 passed)
130 steps (130 passed)
3m18.62s (72.56Mb)
The command "moodle-plugin-ci behat" exited with 0.
155.14s$ moodle-plugin-ci behat --profile chrome
 RUN  Behat features for qtype_formulas
Running single behat site:
Moodle 3.8.3+ (Build: 20200618), 898415efec81bc62bde20b862d1b139407a7329a
Php: 7.3.14, pgsql: 9.6.17, OS: Linux 5.0.0-1031-gcp x86_64
Server OS "Linux", Browser: "chrome"
Browser specific fixes have been applied.
Started at 23-06-2020, 04:10
...................................................................... 70
............................................................
7 scenarios (7 passed)
130 steps (130 passed)
2m24.68s (72.60Mb)

**Comment by PhilippImhof** [comment]
This will be fixed with #35
