### ISSUE TITLE
formatcheck error

### ISSUE THREAD

**Issue by andreas-web** [FormulasQuestion/moodle-qtype_formulas#16]
Hello,

I've got an error in my console:
Uncaught SyntaxError: Unexpected token 'else'

The brackets seem to be missing in the last lines of formatcheck.js:

```
window.onload = (function(oldfunc, newfunc) {
    if (oldfunc && typeof oldfunc == 'function')
        return function() { oldfunc(); newfunc(); }
    else
        return newfunc;
})(window.onload, function() { formulas_format_check(); });
```

-->

```
window.onload = (function(oldfunc, newfunc) {
    if (oldfunc && typeof oldfunc == 'function') {
        return function() { oldfunc(); newfunc(); }
    } else {
        return newfunc;
    }
})(window.onload, function() { formulas_format_check(); });
```

Moodle seems to need these brackets.

**Comment by PhilippImhof** [comment]
Thanks for reporting.

This seems to be browser dependent; the code works fine on my system. Nevertheless, those brackets do not hurt and IMHO it is always safer to have them. Also, Moodle code style complains if they are missing. So this will be fixed soon.
