### ISSUE TITLE
Scheduled task failed: Updating overdue quiz attempts , Variable 'R' has not been defined . in substitute_vname_by_variables

### ISSUE THREAD

**Issue by nadavkav** [FormulasQuestion/moodle-qtype_formulas#18]
Every few weeks we get the errors reported at CRON level for the scheduled task "Updating overdue quiz attempts".
My guess is that teachers change the question after the quiz started, and student's attempt a version of the question without the relevant variables.

CRON log debugging:
php admin/tool/task/cli/schedule_task.php --execute="\mod_quiz\task\update_overdue_attempts" --showdebugging 
Execute scheduled task: Updating overdue quiz attempts (mod_quiz\task\update_overdue_attempts)
  Looking for quiz overdue quiz attempts...
... used 140 dbqueries
... used 1.14586186409 seconds
Scheduled task failed: Updating overdue quiz attempts (mod_quiz\task\update_overdue_attempts),Variable 'R' has not been defined. in substitute_vname_by_variables
Backtrace:
* line 595 of /question/type/formulas/variables.php: call to qtype_formulas_variables->substitute_vname_by_variables()
* line 873 of /question/type/formulas/question.php: call to qtype_formulas_variables->evaluate_general_expression()
* line 723 of /question/type/formulas/question.php: call to qtype_formulas_question->get_evaluated_answer()
* line 835 of /question/type/formulas/question.php: call to qtype_formulas_question->grade_responses_individually()
* line 266 of /question/behaviour/adaptivemultipart/behaviour.php: call to qtype_formulas_question->grade_parts_that_can_be_graded()
* line 370 of /question/behaviour/adaptivemultipart/behaviour.php: call to qbehaviour_adaptivemultipart->process_parts_that_can_be_graded()
* line 203 of /question/behaviour/adaptivemultipart/behaviour.php: call to qbehaviour_adaptivemultipart->process_finish()
* line 1355 of /question/engine/questionattempt.php: call to qbehaviour_adaptivemultipart->process_action()
* line 1395 of /question/engine/questionattempt.php: call to question_attempt->process_action()
* line 859 of /question/engine/questionusage.php: call to question_attempt->finish()
* line 2171 of /mod/quiz/attemptlib.php: call to question_usage_by_activity->finish_all_questions()
* line 2005 of /mod/quiz/attemptlib.php: call to quiz_attempt->process_finish()
* line 79 of /mod/quiz/cronlib.php: call to quiz_attempt->handle_if_time_expired()
* line 61 of /mod/quiz/classes/task/update_overdue_attempts.php: call to mod_quiz_overdue_attempt_updater->update_overdue_attempts()
* line 163 of /admin/tool/task/cli/schedule_task.php: call to mod_quiz\task\update_overdue_attempts->execute()

**Comment by PhilippImhof** [comment]
Thanks for reporting this.

Unfortunately, I think there is not much we can do about it. Loading and/or displaying the question will ultimately fail if it refers to variables that are no longer defined. People must be extremely careful while modifying questions which have already been attempted.

Maybe I can find a more elegant solution to this in the future.

**Comment by PhilippImhof** [comment]
Closing this, because it is a consequence of the behaviour described in #93. It will be fixed with the new major version.
