### ISSUE TITLE
Should the relative error variable in grading criterion accept "== 0"?

### ISSUE THREAD

**Issue by harriholappa** [FormulasQuestion/moodle-qtype_formulas#22]
Should the relative error variable in grading criterion accept "== 0"? We tested a simple multiplying and division question with the Number answer type, and the correct answer was marked as incorrect in the preview window - seemingly randomly. The problem vanished when we switched the grading criterion to "Relative error < 0.001" or "Absolute error < 0.000001. Is this a bug or working as intended?

The random variables we used were:
firstthing={16,24,28,32,48,56,64};
secondthing={8,10,20,40}

The global variables we used were:
answer=(4*firstthing)/secondthing*7

**Comment by jmvedrine** [comment]
This is in fact a common problem with computer calculations. All numbers are converted to binary representations before the calculation occur so this introduce small errors and and a result that "should be" exactly equal to some number is in fact "slightly different". So it is advisable to prefer testing inferior to a very small number than testing equal to zero.
This problem appear random but in fact it is not : it depends if the decimal number has an exact representation in base 2 or only an approximation.

**Comment by harriholappa** [comment]
Thank you for clarifying this!
