### ISSUE TITLE
atan2(): Problems marking angle questions.

### ISSUE THREAD

**Issue by scarral** [FormulasQuestion/moodle-qtype_formulas#27]
I have many formula type questions with random parameters where the students have to do many calculations with complex numbers. One of these calculations involves calculating the angle. Since it's important to keep the information about which quadrant the complex number is in (they have to add the complex numbers afterwards, so it's important to know the signs of the real and imaginary parts), I've been using the atan2() function. Last year when I was developing these questions, I believe that the documentation of the atan2() read something like this: "...this function delivers a positive angle from the positive x axis in counterclockwise direction" or so. We had a Moodle update recently, and now it reads: "...returns a numeric value between -π and π". Since the parameters are random, I cannot tell in advance what angle I'll get and in which quadrant it will be. 

The problem is the following: the atan2() function sometimes returns a positive (counterclockwise) angle and sometimes a negative (clockwise) angle. If Moodle calculates a positive angle (for instance +10°) and the student inputs the corresponding (same) negative angle (in this case -350°, which is strictly speaking correct), Moodle marks that part of the question as incorrect. 

What can I do to get Moodle to mark a correct angle (in this case either +10° or -350°) as correct?

Say my calculation code looks like this: answer=atan2(y,x);

Is it possible to do one of the following (if so, how)?:

- Give 3 possible answers in the corresponding Part X, so that when the student inputs one of the thee the answer is marked as correct. In this case the calculation code could look like this:
answer1=atan2(y,x);
answer2=360+answer1; // if answer1 was negative, answer2 is positive
answer3=answer1-360; // if answer1 was positive, answer3 is negative
and the thee possible answers would be answer1, answer2 and answer3. 

- write an if clause in the calculation code like this:
answer=atan2(y,x);
if (answer<0)
   {
   answer1=360+answer; // the previously negative angle is now positive
   }
end
or otherwise force all negative angles to be converted to positive angles.

- is there another function other than atan2() that would give me positive angles always?

Thanks for your help!

**Comment by PhilippImhof** [comment]
AFAICS you could just use `(360 + answer) % 360`. For angles from 0 to 360 degrees, that will not change the result. For angles between 0 and -360 degrees, the result will then be between 0 and 360.

**Comment by PhilippImhof** [comment]
Do not hesitate to open this again, if you think that your issue has not been solved with the answer above.
