### ISSUE TITLE
Moodle cron halts with students erroneous formulas

### ISSUE THREAD

**Issue by nadavkav** [FormulasQuestion/moodle-qtype_formulas#3]
When students input formulas with errors, the following line:
https://github.com/jmvedrine/moodle-qtype_formulas/blob/master/variables.php#L945
Throw and exception that halt Moodle's cron with errors and all further cron task are left unprocessed 
See discussion:
https://moodle.org/mod/forum/discuss.php?d=340646#p1385674

**Comment by jmvedrine** [comment]
Hello Nadav,
Unfortunately I am now retired and I stopped all Moodle coding ( I don't even have a Moodle site running) so I will no be able to study and try to solve this problem.
Just an idea : why this only happen during cron ? Surely the student bad answer is also evaluated when submitted, what is different during cron ?

**Comment by nadavkav** [comment]
:balloon: Happy retirement :tada: :balloon: 
Just found out that probably we are bad, as one of our team modified the variables.php file and probably broke something. still investigating this.

Thank you for a great question type. It is widely used and very much appreciated!

**Comment by jmvedrine** [comment]
Thanks ! As I moved near the Mediterranean Sea, I am now enjoying :ocean: :sunny: :palm_tree: :sailboat: :tropical_drink: (this largely explains why I don't have any time left for computing :wink: )

**Comment by nadavkav** [comment]
It is an inspiration to us all :-)

**Comment by jmvedrine** [comment]
I think I can close this.
