### ISSUE TITLE
import and export features should use the @_file_upload tag

### ISSUE THREAD

**Issue by ewallah** [FormulasQuestion/moodle-qtype_formulas#6]
The behat import feature uploads a file and the export feature downloads a file.  This works fine when selenium is running in the same machine where the tests are running. But when different machines are used, the steps fail. 
To avoid this, there is a @_file_upload tag. When this tag is added to the 2 files, all tests run fine, even using different machines.

**Comment by jmvedrine** [comment]
Hello ewallah,
Thanks a lot for pointing that. I was puzzled by Behat tests working on my machine and not on Travis.
I will fix this problem.

**Comment by ewallah** [comment]
Hello Jean-Michel,

late THX for the fix.

One other thing: download between "4200" and "4300" bytes does not work on Travis (and my test servers), perhaps due to the compression. Sometimes (for performance reasons) one can choose to disable  compression.

When I change the 4300 into 5300, all behat tests on Travis pass: cfr. https://travis-ci.org/ewallah/moodle-qtype_formulas/jobs/497798921#L1407
