### ISSUE TITLE
How to combine formulas with MathJax matrix display?

### ISSUE THREAD

**Issue by euneuber** [FormulasQuestion/moodle-qtype_formulas#8]
Hi,
there is a beautiful question on the [moodle.org plugin page](https://moodle.org/plugins/qtype_formulas):
![formulas 2](https://user-images.githubusercontent.com/3296589/51707847-8abb0500-2022-11e9-84f6-5c6e769f6e65.png)

can please point me to the question settings?

I tried to rebuild the question but it breaks the MathJax display...

Thanks!

**Comment by jmvedrine** [comment]
Hello This is one of the sample questions included in the question/type/formulas/samples/sample-formulas-questions.xml file. The name of this question is "5.3: Possible question type - matrix".
You can find this file in this Github repo if you don't have access to it on your Moodle server:
https://github.com/jmvedrine/moodle-qtype_formulas/blob/master/samples/sample-formulas-questions.xml
This question was created some years ago by Hon Wai Lau when MathJax wasn't available in Moodle but according to my tests it still works well with MathJax display. If you have some questions or if the display is broken on your website, don't hesitate to post a message here and I will try to help.
 Jean-Michel Védrine

**Comment by euneuber** [comment]
Hi,
Thank you for your fast response!
I found your question and can confirm it still works in Moodle 3.4.x
![grafik](https://user-images.githubusercontent.com/3296589/51901360-bf7ae380-23b7-11e9-809f-72aad199c161.png)

**Comment by jmvedrine** [comment]
Than ks for the report. I will close this.
